#!/bin/bash

# Input arguments
NP=${1?Error: Number of processes for mpirun not given. Please append as number.}

# Source libraries
echo -----------------------
echo sourcing libraries: source ./load_libraries
source ./load_libraries

# Setting namelist
ln -sf namelist.input.pytools namelist.input

# Run WRF
echo ------------------------
echo running wrf:
export OMP_NUM_THREADS=1
cmd=(mpirun -np "$NP" -ppn "$NP" -bind-to core -map-by socket ./wrf.exe)
printf '%q ' "${cmd[@]}"
echo
"${cmd[@]}"
