#!/bin/bash

# Input argument
NP=${1?Error: Number of processes for mpirun not given. Please append as number.}

# Run without hangup
# (echo l | nohup ./runall_real 16) &

# Source libraries
echo -----------------------
echo sourcing libraries: source ./load_libraries
source ./load_libraries

# Copying/linking metgrid files into directory
echo --------------------------
echo Listing WPS metgrid files:
ls ../../WPS/met_em* 
read -p "Copy (c) or link (l) metgrid files? " answer
case ${answer:0:2} in
    c )
        echo Copy
        echo cp ../../WPS/met_em* .
        cp ../../WPS/met_em* .
    ;;
    l )
        echo Link
        echo ln -sf ../../WPS/met_em* .
        ln -sf ../../WPS/met_em* .
    ;;
    * )
        echo None of the above
    ;;
esac

# Run real
echo ------------------------
echo running real: mpirun -np $NP ./real.exe
mpirun -np $NP ./real.exe

