#!/bin/bash

# Input arguments
WPS_PATH=${1?Error: WPS path not given. Please append as string.}
NP=${2?Error: Number of processes for mpirun not given. Please append as number.}

# Source libraries
echo -----------------------
echo sourcing libraries: source ./load_libraries
source ./load_libraries

# Setting namelist
ln -sf namelist.input.pytools namelist.input

# Copying/linking metgrid files into directory
echo --------------------------
echo linking metgrid files: ln -sf $WPS_PATH/met_em* .
ln -sf $WPS_PATH/met_em* .

# Run real
echo ------------------------
echo running real:
export OMP_NUM_THREADS=1
cmd=(mpirun -np "$NP" -ppn "$NP" -bind-to core -map-by socket ./real.exe)
printf '%q ' "${cmd[@]}"
echo
"${cmd[@]}"
