#!/bin/bash

# Input argument
NP=${1?Error: Number of processes for mpirun not given. Please append as number.}

# Run without hangup
# (echo l | nohup ./runall_real 16) &

# Source libraries
echo -----------------------
echo sourcing libraries: source ./load_libraries
source ./load_libraries

# Run WRF
echo ------------------------
echo running wrf: mpirun -np $NP ./wrf.exe
mpirun -np $NP ./wrf.exe

